#!/usr/bin/env bash
# Install nginx on web-01
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/listen\(.*\);/listen 80;/g' /etc/nginx/sites-available/default
sudo chmod 666 /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo nginx -s reload
