#!/usr/bin/bash
# Double the number of webservers
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chmod 666 /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo mkdir -p /var/www/abeermosaad.tech/html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/abeermosaad.tech/html/custom_404.html > /dev/null 2>&1
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=mN_jYKCTEwU&t=10s;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\tinternal;\n\t\troot /var/www/abeermosaad.tech/html;\n\t}' /etc/nginx/sites-available/default
sed -i "/server {/a\n\n\tadd_header X-Served-By $hostname;" /etc/nginx/sites-available/default
sudo srevice nginx start
sudo nginx -s reload
