#!/usr/bin/env bash
# Configure nginx to listen to port 80
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
