#!/usr/bin/env bash
# creat script that uses the if, elif, while and else statements
cnt=1
while [ $cnt -le 10 ]
do
	if [ $cnt == 4 ]
	then
		echo "bad luck"
	elif [ $cnt == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((cnt++))
done
