#!/usr/bin/env bash
# configures the container to fit the above requirements
sudo useradd nginx
sed -i 's/^user.*;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo docker stop 3617bb0db964
sudo service nginx start
sudo nginx -s reload


